### ISSUE TITLE
Table definition and data are deleted after back navigation

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material-table#48] opened 2017-03-11 09:22 UTC
Hi together
After update the table-addin to version 1.0-SNAPSHOT or 1.0-rc4 the table-definition is deleted after back navigation. I can't reload it anymore. Thank you for resolving this issue.

![10-03-_2017_18-52-38_2](https://cloud.githubusercontent.com/assets/24357072/23822050/71c705b6-0644-11e7-9aa0-2ff9941e70f8.gif)

**Comment by reofake** [comment] 2017-03-14 10:50
I got the same problem, and an Exception log in browser console.

**Comment by kevzlou7979** [comment] 2017-03-21 11:17
I just tried to debug where is the root cause of the problem. It was on the ```AbstractDataView``` on method ```addHeader(int index, TableHeader header, Column<T, ?> column)``` line https://github.com/GwtMaterialDesign/gwt-material-table/blob/release_1.0/src/main/java/gwt/material/design/client/data/AbstractDataView.java#L1852 which has an ```IndexOutBounceException```.

**Comment by kevzlou7979** [comment] 2017-03-21 13:02
Fixed  via https://github.com/GwtMaterialDesign/gwt-material-table/commit/8ac86be6f40f558c7fbb8f22ed083b4536b8a1cd.

See working demo here : http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#datatable

Screenshot:
![table](https://cloud.githubusercontent.com/assets/3138071/24148059/075b38f0-0e78-11e7-8798-ac50db0b3142.gif)

**Comment by BenDol** [comment] 2017-03-21 22:07
@HoochSDS make sure you are using the temporary solution for tables load handler `setLoadHandler` this will ensure the table doesn't constantly reset onAttach/onLoad.

**Comment by HoochSDS** [comment] 2017-03-22 20:52
@BenDol, In a GWTP-Application (Data table 1.0-SNAPSHOT) even with a table load handler  
the table is always cleared and you get an Exception. (The same as described in fix 8ac86be)

**Code** (GWTP-Viewmodul):
```
  @UiField
  MaterialDataTable<Person> personTable;

    personTable.setLoadedCallback(new LoadedCallbackImpl() {
      @Override
      public void onLoaded() {
        super.onLoaded();
        initTable();      // --> personTable.addColumn(...);
      }
    });
```
**Exception**:
Could not setup AbstractDataTable due to previous errors.
Exception: java.lang.IndexOutOfBoundsException
Error: java.lang.IndexOutOfBoundsException
    at E5f_g$.Hj_g$ [as createError_0_g$] (App-0.js:5484:10)
    at E5f_g$.Rj_g$ [as initializeBackingError_0_g$] (App-0.js:5539:43)
    at E5f_g$.yj_g$ (App-0.js:5372:8)
    at E5f_g$.ck_g$ (App-0.js:5620:9)
    at E5f_g$.kk_g$ (App-0.js:5667:9)

I don't understand where to place the table initialize Routine, if onLoaded() in ```setLoadedCallback()``` is called on every onAttach().
Thanks

**Comment by BenDol** [comment] 2017-03-23 06:37
IndexOutOfBoundsException seems like a different issue. Can you provide a full stack trace for that exception?

**Comment by HoochSDS** [comment] 2017-03-23 16:16
@BenDol, The Exception throws after the Backnavigation. Here the full stack trace.
But again, how to prevent the table from being deleted after each onAttach(). (As it used to be in 1.0-rc3)
Thanks

**Stack Trace:**
```
Default type of navbar was applied
Could not setup AbstractDataTable due to previous errors.
Exception: java.lang.IndexOutOfBoundsException
Error: java.lang.IndexOutOfBoundsException
    at Q5f_g$.Hj_g$ [as createError_0_g$] (App-0.js:5484:10)
    at Q5f_g$.Rj_g$ [as initializeBackingError_0_g$] (App-0.js:5539:43)
    at Q5f_g$.yj_g$ (App-0.js:5372:8)
    at Q5f_g$.ck_g$ (App-0.js:5620:9)
    at Q5f_g$.kk_g$ (App-0.js:5667:9)
    at Q5f_g$ (App-0.js:74377:9)
    at x2f_g$.Kpd_g$ [as checkIndexBoundsForInsertion_0_g$] (App-0.js:33178:18)
    at x2f_g$.Ipd_g$ [as adjustIndex_0_g$] (App-0.js:33160:8)
    at x2f_g$.Spd_g$ [as insert_1_g$] (App-0.js:33219:27)
    at x2f_g$.LLe_g$ [as insert_1_g$] (App-0.js:49301:30)
    at x2f_g$.Rpd_g$ [as insert_0_g$] (App-0.js:33215:8)
    at x2f_g$.KLe_g$ [as insert_3_g$] (App-0.js:49290:8)
    at x2f_g$.E2f_g$ [as insert_11_g$] (App-0.js:73651:28)
    at ymf_g$.cff_g$ [as addHeader_0_g$] (App-0.js:59157:23)
    at ymf_g$.egf_g$ [as insertColumn_0_g$] (App-0.js:59642:10)
    at N0f_g$.A$f_g$ [as insertColumn_0_g$] (App-0.js:72453:22)
    at N0f_g$.W0f_g$ [as insertColumn_0_g$] (App-0.js:73137:34)
    at N0f_g$.JZf_g$ [as addColumn_1_g$] (App-0.js:72249:8)
    at M1h_g$.S1h_g$ [as initPersTable_0_g$] (App-0.js:97325:25)
    at o2h_g$.p2h_g$ [as onLoaded_0_g$] (App-0.js:97521:23)
    at N0f_g$.R$f_g$ [as onLoad_1_g$] (App-0.js:72548:34)
    at N0f_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32934:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at VGf_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at VGf_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at vNf_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at vNf_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at $Ad_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at $Ad_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at DVe_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at DVe_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at VGf_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at VGf_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at vNf_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at vNf_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33489:10)
    at Fqd_g$ (App-0.js:33445:14)
    at $Ad_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33110:3)
    at $Ad_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:32933:8)
    at $Ad_g$.npd_g$ [as setParent_0_g$] (App-0.js:33029:12)
    at $Ad_g$.vpd_g$ [as adopt_0_g$] (App-0.js:33097:14)
    at $Ad_g$.Hpd_g$ [as add_7_g$] (App-0.js:33155:8)
    at $Ad_g$.aBd_g$ [as add_5_g$] (App-0.js:34379:8)
    at VJh_g$.Dze_g$ [as setInSlot_4_g$] (App-0.js:45175:67)
    at FJh_g$.Aye_g$ [as setInSlot_1_g$] (App-0.js:44805:25)
    at FJh_g$.zye_g$ [as setInSlot_0_g$] (App-0.js:44794:8)
    at NHe_g$.OHe_g$ [as execute_1_g$] (App-0.js:47808:30)
    at AZ_g$ (App-0.js:11152:27)
    at eZ_g$ (App-0.js:10874:9)
    at VY_g$._Y_g$ [as flushPostEventPumpCommands_0_g$] (App-0.js:10966:5)
    at rZ_g$.sZ_g$ [as execute_2_g$] (App-0.js:11105:22)
    at YY_g$ (App-0.js:10842:19)
    at LX_g$ (App-0.js:10586:28)
console.groupEnd
```
**Call Stack:**

![callstack](https://cloud.githubusercontent.com/assets/24357072/24257682/ccfba4fe-0feb-11e7-8224-5f5981d46a03.jpg)

**Comment by eliseurm** [comment] 2017-04-24 13:26
Hi, I have this same problem too. #19 #48

Do you have any solutions to the problem?

**Comment by kevzlou7979** [comment] 2017-04-25 03:37
Reverted https://github.com/GwtMaterialDesign/gwt-material-table/commit/0d7c279fe5dce78eacda05b7a17e8c74fb70ce2f

**Comment by HoochSDS** [comment] 2017-04-27 13:30
Hi
In a GWTP-Application, with each Backnavigation, the onAttach() method (GWTP-View) is called and 
clears the Table colums and rows. Dispite the fix #0d7c279

And also after each Backnavigation, the temporary workaround for Table-addColumn callback definition see #28 from @BenDol is called too.
```
table.setLoadedCallback(()-> {
   table.addColumn(...);
   ...
});
```
Since GMD issue #621 we can't go back to GMD-Table rc3 anymore.  :confused:
Using: Current SNAPSHOT - 2.0-SNAPSHOT

Thank you very much

**Comment by BenDol** [comment] 2017-04-27 22:10
Where are you calling setLoadCallback?

**Comment by HoochSDS** [comment] 2017-04-28 15:58
Hi, @BenDol 
I wrote a gwtp test-program to show you what i'm meaning exactly if i say 
"GWT-table since rc4 is deleted after backnavigation". I can't use GWT-Table anymore.
 
Using: GWT-Material - 2.0-SNAPSHOT
    <gwt.version>2.8.0</gwt.version>
    <gwtp.version>1.6</gwtp.version>
    <gin.version>2.1.2</gin.version>
    <guice.version>3.0</guice.version>


Thank you very much for your help

![gwt_table](https://cloud.githubusercontent.com/assets/24357072/25536294/9546386a-2c3a-11e7-8d5b-5875d793c18d.gif)

An this are the GWTP-Files:

**TestView.ui.xml:**
```
<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
             xmlns:m="urn:import:gwt.material.design.client.ui"
             xmlns:m.table="urn:import:gwt.material.design.client.ui.table"
>
  <m:MaterialPanel ui:field="panel" marginTop="64">
    <m:MaterialRow>
      <m.table:MaterialInfiniteDataTable m:id="customTable" ui:field="table"
                                         height="calc(50vh)"
                                         useStickyHeader="true"
                                         useCategories="false"
                                         useRowExpansion="false"
                                         selectionType="SINGLE"/>
    </m:MaterialRow>
  </m:MaterialPanel>
</ui:UiBinder>
```
**TestView.java:**
```
public class TestView extends ViewImpl implements TestPresenter.MyView {

  public boolean loaded = false;

  interface Binder extends UiBinder<MaterialPanel, TestView> {
  }
  @UiField
  MaterialInfiniteDataTable<FallDTO> table;

  @Inject
  TestView(Binder binder) {
    initWidget(binder.createAndBindUi(this));

    table.setLoadedCallback(() -> {
      if (!loaded) {
        loaded = true;  // with no loaded flag you got a exception
                        // after backnavigation
        // Add the tables columns
        table.addColumn(new TextColumn<FallDTO>() {
          @Override
          public String getValue(FallDTO object) {
            return object.getPersVorname();
          }
        }, "Firstname");

        table.addColumn(new TextColumn<FallDTO>() {
          @Override
          public String getValue(FallDTO object) {
            return object.getPersName();
          }
        }, "Name");
      }
    });
  }

  @Override
  protected void onAttach() {
    // Since GWT-Table rc4 after each backnavigation
    //   --> The Table-colums and rows will be deleted?
    //   --> And the table.setLoadedCallback() is being called?
    super.onAttach();
  }
}
```

**TestPresenter.java**
```
public class TestPresenter extends Presenter<TestPresenter.MyView, TestPresenter.MyProxy> {
  interface MyView extends View {
  }

  @NameToken(NameTokens.TEST)
  @ProxyStandard
  interface MyProxy extends ProxyPlace<TestPresenter> {
  }

  @Inject
  TestPresenter(EventBus eventBus, MyView view, MyProxy proxy) {
    super(eventBus, view, proxy, ApplicationPresenter.SLOT_MAIN);
  }

  @Override
  protected void onReveal() {
    super.onReveal();
    SetMenuBarTitleEvent.fire("Test", this);
  }
}
```

**Comment by BenDol** [comment] 2017-04-29 02:16
The exception issue has been fixed in the latest commit, you can remove the `if(!loaded)` check now and everything should work fine.

**Comment by HoochSDS** [comment] 2017-04-29 09:24
Sorry, nothing has changed with (SNAPSHOT gwt-material-table-2.0-20170429.020453-6.jar)
The gwtp onAttach() is still clearing the table and calling the table.setLoadedCallback() every backnavigation.
```
Could not setup AbstractDataTable due to previous errors.
  ZIh_g$	
  wdh_g$	
  Kch_g$	
  Jch_g$	
  fdh_g$	
  n1f_g$	
  fpd_g$	
  Jqd_g$	
  Fqd_g$	
  xpd_g$	
  fpd_g$	
  Jqd_g$	
  Fqd_g$	
  xpd_g$	
  fpd_g$	
  npd_g$	
  vpd_g$	
  Hpd_g$	
  aBd_g$	
  Xze_g$	
  Uye_g$	
  Tye_g$	
  gIe_g$	
  AZ_g$	
  eZ_g$	
  _Y_g$	
  sZ_g$	
  YY_g$	
  LX_g$	
  OX_g$	
  (anonymous function)	
  callback_0_g$	
>Exception: java.lang.IndexOutOfBoundsException
  Error: java.lang.IndexOutOfBoundsException
    at h8f_g$.Hj_g$ [as createError_0_g$] (App-0.js:5516:10)
    at h8f_g$.Rj_g$ [as initializeBackingError_0_g$] (App-0.js:5571:43)
    at h8f_g$.yj_g$ (App-0.js:5404:8)
    at h8f_g$.ck_g$ (App-0.js:5652:9)
    at h8f_g$.kk_g$ (App-0.js:5699:9)
    at h8f_g$ (App-0.js:75398:9)
    at R4f_g$.Kpd_g$ [as checkIndexBoundsForInsertion_0_g$] (App-0.js:33255:18)
    at R4f_g$.Ipd_g$ [as adjustIndex_0_g$] (App-0.js:33237:8)
    at R4f_g$.Spd_g$ [as insert_1_g$] (App-0.js:33296:27)
    at R4f_g$.dMe_g$ [as insert_1_g$] (App-0.js:49516:30)
    at R4f_g$.Rpd_g$ [as insert_0_g$] (App-0.js:33292:8)
    at R4f_g$.cMe_g$ [as insert_3_g$] (App-0.js:49505:8)
    at R4f_g$.Y4f_g$ [as insert_11_g$] (App-0.js:74673:28)
    at fnf_g$.Mff_g$ [as addHeader_0_g$] (App-0.js:59728:23)
    at fnf_g$.Ngf_g$ [as insertColumn_0_g$] (App-0.js:60213:10)
    at f4f_g$.Y0f_g$ [as insertColumn_0_g$] (App-0.js:73475:22)
    at f4f_g$.o3f_g$ [as insertColumn_0_g$] (App-0.js:74159:34)
    at f4f_g$.j0f_g$ [as addColumn_1_g$] (App-0.js:73271:8)
    at kXi_g$.CZi_g$ [as lambda$0_77_g$] (App-0.js:100389:21)
    at PZi_g$.QZi_g$ [as onLoaded_0_g$] (App-0.js:100472:25)
    at f4f_g$.n1f_g$ [as onLoad_1_g$] (App-0.js:73570:34)
    at f4f_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:33011:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33566:10)
    at Fqd_g$ (App-0.js:33522:14)
    at UQf_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33187:3)
    at UQf_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:33010:8)
    at Iqd_g$.Jqd_g$ [as execute_4_g$] (App-0.js:33566:10)
    at Fqd_g$ (App-0.js:33522:14)
    at XVe_g$.xpd_g$ [as doAttachChildren_0_g$] (App-0.js:33187:3)
    at XVe_g$.fpd_g$ [as onAttach_0_g$] (App-0.js:33010:8)
    at XVe_g$.npd_g$ [as setParent_0_g$] (App-0.js:33106:12)
    at $Ad_g$.vpd_g$ [as adopt_0_g$] (App-0.js:33174:14)
    at $Ad_g$.Hpd_g$ [as add_7_g$] (App-0.js:33232:8)
    at $Ad_g$.aBd_g$ [as add_5_g$] (App-0.js:34456:8)
    at mMh_g$.Xze_g$ [as setInSlot_4_g$] (App-0.js:45366:67)
    at YLh_g$.Uye_g$ [as setInSlot_1_g$] (App-0.js:44996:25)
    at YLh_g$.Tye_g$ [as setInSlot_0_g$] (App-0.js:44985:8)
    at fIe_g$.gIe_g$ [as execute_1_g$] (App-0.js:48017:30)
    at AZ_g$ (App-0.js:11224:27)
    at eZ_g$ (App-0.js:10946:9)
    at VY_g$._Y_g$ [as flushPostEventPumpCommands_0_g$] (App-0.js:11038:5)
    at rZ_g$.sZ_g$ [as execute_2_g$] (App-0.js:11177:22)
    at YY_g$ (App-0.js:10914:19)
    at LX_g$ (App-0.js:10658:28)
    at OX_g$ (App-0.js:10714:16)
    at App-0.js:10694:14
    at callback_0_g$ (App-0.js:10965:38)
    ZIh_g$	
    _Ih_g$	
    $Ih_g$	
    wdh_g$	
    Kch_g$	
    Jch_g$	
    fdh_g$	
    n1f_g$	
    fpd_g$	
    Jqd_g$	
    Fqd_g$	
    xpd_g$	
    fpd_g$	
    Jqd_g$	
    Fqd_g$	
    xpd_g$	
    fpd_g$	
    npd_g$	
    vpd_g$	
    Hpd_g$	
    aBd_g$	
    Xze_g$	
    Uye_g$	
    Tye_g$	
    gIe_g$	
    AZ_g$	
    eZ_g$	
    _Y_g$	
    sZ_g$	
    YY_g$	
    LX_g$	
    OX_g$	
    (anonymous function)	
    callback_0_g$	
  <console.groupEnd

```

**Comment by BenDol** [comment] 2017-04-29 10:43
Seems the latest snapshot hasn't been updated.

**Comment by BenDol** [comment] 2017-04-29 14:10
I changed the demo to work like the way you described using the latest changes too:
http://i.imgur.com/nIfxfb1.mp4

**Comment by HoochSDS** [comment] 2017-04-30 12:40
I checked the new snapshot (gwt-material-table-2.0-20170429.105042-8.jar) but with no success.
Nothing has changed. If i reach the breakpoint in the onAttach() method after backnavigation, the table is already cleared.

**Comment by kevzlou7979** [comment] 2017-05-01 06:28
@BenDol  I tested the update on DataTable and it works well. @HoochSDS  Here's the snapshot repository https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/

**Comment by kevzlou7979** [comment] 2017-05-01 06:31
Checkout the recent update on http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#datatable and do the back and forth navigation

**Comment by HoochSDS** [comment] 2017-05-01 13:21
Hi
I see the SNAPSHOT (gwt-material-table-2.0-20170429.105042-8.jar) is working well in your program-architecture.

In the GWTP model-view-presenter architecture (MVP) it does not.

The AbstractDataTable **onUnload()** method is called from the Widget class com.google.gwt.user.client.ui.Widget **onDetach()** method on every backnavigation in GWTP, 
and destroyed because of the new destroy() method the GWT-Datatable. The setup Flag is set to false, and that is the reason for the Exception "Could not setup AbstractDataTable due to previous errors" 

Is it possible to remove the  Override onUnload() in GWT-Datatable again?
Thanks

AbstractDataTable :
```
    @Override
    protected void onUnload() {
        super.onUnload();

        destroy();		
        setup = false;
    }

    @Override
    public void destroy() {
        rows.clearComponents();
        categories.clearComponents();

        columns.clear();
        headers.clear();
        headerRow.clear();

        rendering = false;

        container.off("." + id);
        tableBody.off("." + id);
        $(window()).off("." + id);
    }
```
![code](https://cloud.githubusercontent.com/assets/24357072/25580351/a0aa0e32-2e80-11e7-92c4-276723abd914.jpg)

**Comment by BenDol** [comment] 2017-05-01 14:02
This is the correct behaviour. When the table is unloaded it is destroyed and when it is reattached it is loaded again. There should not be any exception thrown there. Perhaps you can share a small project that reproduces the issue that we can take a look at since we are unable to reproduce the issue on our end using GWTP.

**Comment by BenDol** [comment] 2017-05-01 14:08
Also it might pay to print a detailed stack of the exception showing file names and line numbers.

**Comment by HoochSDS** [comment] 2017-05-01 15:12
The callback-flag (loaded) is not the question anymore, the question is why do you unload (destroy()) the table on each Widget detach (onDetach()). This means you have to redefine and reload the table on every backnavigation. In rc3 it was not necessary.

**Comment by BenDol** [comment] 2017-05-01 15:31
When the table onUnload's it made sense that it should require the table to rebuild itself upon calling onLoad again, since it has taken itself off the DOM. However I can see the need to keep it loaded during this process (even though it can cause strange issues when not done correctly). I have added a new option `destroyOnUnload` that will default to `false`.

I would still like to know why an exception is throwing for you since it should be gracefully reloading. Can you provide me a detailed stack trace?

**Comment by HoochSDS** [comment] 2017-05-01 16:13
Sorry for misunderstanding, there is no exception anymore.

**Comment by HoochSDS** [comment] 2017-05-01 16:57
suggestion
```rendering``` flag is only set true on **renderRows()**.
If you haven't rows to render. Are the table columns render after detach?

**Comment by BenDol** [comment] 2017-05-01 19:11
Will take a look at that use case. Thanks and glad it is working for you now.

**Closed** 2017-05-02 18:22 UTC
Labels: bug, ready
