### ISSUE TITLE
MaterialDataPager with remote filtering MaterialDataTable.

### ISSUE THREAD

**Issue by phisoftware** [GwtMaterialDesign/gwt-material-table#132] opened 2018-01-15 14:37 UTC
The bellow function is into in the MaterialDataPager class.

/**
 * Load the datasource within a given offset and limit
 */
protected void doLoad(int offset, int limit) {
    this.offset = offset;

    // Check whether the pager has excess rows with given limit
    if (isLastPage() & isExcess()) {
        // Get the difference between total rows and excess rows
        limit = totalRows - offset;
    }

    int finalLimit = limit;
    dataSource.load(new LoadConfig<>(offset, limit, table.getView().getSortContext(),
            table.getView().getOpenCategories()), new LoadCallback<T>() {
        @Override
        public void onSuccess(LoadResult<T> loadResult) {
            totalRows = loadResult.getTotalLength();
            table.setVisibleRange(offset, finalLimit);
            table.loaded(loadResult.getOffset(), loadResult.getData());
            updateUi();
        }

        @Override
        public void onFailure(Throwable caught) {
            GWT.log("Load failure", caught);
            //TODO: What we need to do on failure? May be clear table?
        }
    });
}

When loadResult size is bigger than its previous size, the visible range will be smaller than row count. soo the table dont show all rows...

finalLimit must be calculated in public void onSuccess(LoadResult<T> loadResult) method...

you can test it with remote filtering data table...

and i cannot Override that doLoad function because declaration of offset, dataSource, totalRows , table are private...

**Comment by kevzlou7979** [comment] 2018-02-10 23:31
Duplicate of https://github.com/GwtMaterialDesign/gwt-material-table/issues/86, will patch this on 2.1

**Closed** 2018-02-13 01:05 UTC
Labels: bug, ready
