### ISSUE TITLE
Selecting CheckBox in GWT material datatable is not selecting row

### ISSUE THREAD

**Issue by sawantrajd** [GwtMaterialDesign/gwt-material-table#156] opened 2018-05-03 18:27 UTC
@kevzlou7979   In GWT material data table if you click on checkbox to select row its not working. If you click on row it select row. In demo also its not working. https://gwtmaterialdesign.github.io/gwt-material-demo/ But its working in infinite data table.

**Comment by sawantrajd** [comment] 2018-05-07 09:11
Anybody have knowledge to resolve this issue. Thanks In advance.

**Comment by sawantrajd** [comment] 2018-05-10 04:34
Can anybody help me to figure out for this issue.

**Comment by BenDol** [comment] 2018-05-10 05:39
Have you tested this on the latest 2.1-SNAPSHOT, I am having trouble reproducing the issue.

**Comment by sawantrajd** [comment] 2018-05-10 06:47
@BenDol Please check it on demo page for Paged data table standard table https://gwtmaterialdesign.github.io/gwt-material-demo/.

thanks

**Comment by BenDol** [comment] 2018-05-10 07:12
Confirmed this has been resolved in the latest 2.1-SNAPSHOT, make sure if you are using a custom `Renderer` for the table that you update it with the `drawSelectionCell` to match that of `BaseRenderer#drawSelectionCell` since a part of the fix was applied there.

**Closed by BenDol** 2018-05-10 07:12 UTC

**Comment by sawantrajd** [comment] 2018-05-10 07:26
@BenDol I am using GWT 2.0 so how can I change it where those changes added for that specific issue?

**Comment by BenDol** [comment] 2018-05-10 11:26
Seems this commit is included in release 2.0-rc7, so should be in the final 2.0 release already.

Edit: Check that you aren't using a custom `Renderer` that is overriding the fix (this is what you are seeing in the demo application, we forgot to update the custom renderer).
